import React from "react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import { formatCurrency } from "../utils/format";

function Report({ facility, equipmentList, calcEnergy, onBack }) {
  const total = equipmentList.reduce((s, it) => s + calcEnergy(it).monthly, 0);

  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(16, 185, 129);
    doc.text("NCEEC Energy Audit Report", pageWidth / 2, 20, {
      align: "center",
    });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(
      "National Centre for Energy Efficiency & Conservation",
      pageWidth / 2,
      27,
      { align: "center" }
    );

    // Facility Info
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Facility: ${facility.name}`, 15, 40);
    doc.setFontSize(10);
    doc.text(
      `Building Type: ${facility.buildingType || "Not specified"}`,
      15,
      46
    );
    doc.text(`Location: ${facility.location}`, 15, 52);
    doc.text(`Area: ${facility.area} m²`, 15, 58);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 15, 64);

    // Summary Box
    doc.setFillColor(240, 253, 244);
    doc.rect(15, 72, pageWidth - 30, 25, "F");
    doc.setFontSize(11);
    doc.setTextColor(21, 128, 61);
    doc.text(`Total Monthly Consumption: ${Math.round(total)} kWh`, 20, 82);
    doc.text(
      `Estimated Monthly Cost: ${formatCurrency(Math.round(total * 95))}`,
      20,
      90
    );

    // Equipment Table
    const tableData = equipmentList.map((item) => [
      item.name,
      item.room || "-",
      item.powerKw.toFixed(3),
      item.qty,
      item.hoursPerDay,
      Math.round(calcEnergy(item).monthly),
      formatCurrency(Math.round(calcEnergy(item).cost)),
    ]);

    doc.autoTable({
      head: [
        [
          "Equipment",
          "Room",
          "Power (kW)",
          "Qty",
          "Hrs/Day",
          "Monthly kWh",
          "Monthly Cost",
        ],
      ],
      body: tableData,
      startY: 105,
      theme: "grid",
      headStyles: { fillColor: [16, 185, 129], textColor: 255 },
      footStyles: {
        fillColor: [240, 253, 244],
        textColor: [21, 128, 61],
        fontStyle: "bold",
      },
      foot: [
        [
          "Total",
          "",
          "",
          "",
          "",
          Math.round(total),
          formatCurrency(Math.round(total * 95)),
        ],
      ],
      styles: { fontSize: 9 },
    });

    // Recommendations
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Recommendations:", 15, finalY);
    doc.setFontSize(10);
    doc.setTextColor(60);
    const recommendations = [
      "• Replace traditional lighting with LED fixtures for 40-50% energy savings",
      "• Optimize HVAC schedules to reduce runtime during unoccupied hours",
      "• Install occupancy sensors in low-traffic areas",
      "• Conduct regular maintenance on all equipment to maintain efficiency",
      "• Consider solar PV installation to offset grid consumption",
    ];
    recommendations.forEach((rec, idx) => {
      doc.text(rec, 15, finalY + 8 + idx * 6);
    });

    // Footer
    const footerY = doc.internal.pageSize.height - 15;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by NCEEC Energy Audit App", pageWidth / 2, footerY, {
      align: "center",
    });

    doc.save(
      `NCEEC_Energy_Audit_${facility.name.replace(/\s+/g, "_")}_${
        new Date().toISOString().split("T")[0]
      }.pdf`
    );
  };

  const exportToCSV = () => {
    const headers = [
      "Equipment",
      "Room",
      "Category",
      "Power (kW)",
      "Quantity",
      "Hours/Day",
      "Daily kWh",
      "Monthly kWh",
      "Monthly Cost (₦)",
    ];
    const rows = equipmentList.map((item) => {
      const energy = calcEnergy(item);
      return [
        item.name,
        item.room || "",
        item.category || "",
        item.powerKw,
        item.qty,
        item.hoursPerDay,
        energy.daily.toFixed(2),
        Math.round(energy.monthly),
        Math.round(energy.cost),
      ];
    });

    // Add summary row
    rows.push([]);
    rows.push([
      "SUMMARY",
      "",
      "",
      "",
      "",
      "",
      "",
      Math.round(total),
      Math.round(total * 95),
    ]);

    const csvContent = [
      [`NCEEC Energy Audit Report - ${facility.name}`],
      [`Building Type: ${facility.buildingType || "Not specified"}`],
      [`Location: ${facility.location}`],
      [`Area: ${facility.area} m²`],
      [`Report Date: ${new Date().toLocaleDateString()}`],
      [],
      headers,
      ...rows,
    ]
      .map((row) => row.join(","))
      .join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `NCEEC_Energy_Audit_${facility.name.replace(/\s+/g, "_")}_${
        new Date().toISOString().split("T")[0]
      }.csv`
    );
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="card">
      <div className="card-body">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">
              Energy Audit Report
            </h2>
            <div className="text-sm text-gray-600 dark:text-gray-300">
              Facility: <span className="font-medium">{facility.name}</span>
            </div>
            <div className="text-xs text-gray-500 dark:text-gray-400">
              Building Type: {facility.buildingType || "Not specified"} •
              Location: {facility.location}
            </div>
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-600 dark:text-gray-300">
              Report Date: <strong>{new Date().toLocaleDateString()}</strong>
            </div>
            <div className="mt-3 flex gap-2">
              <button onClick={exportToPDF} className="btn btn-primary">
                <svg
                  className="w-4 h-4 mr-2 inline"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                  />
                </svg>
                Export PDF
              </button>
              <button onClick={exportToCSV} className="btn btn-secondary">
                <svg
                  className="w-4 h-4 mr-2 inline"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                  />
                </svg>
                Export CSV
              </button>
            </div>
          </div>
        </div>

        <div className="overflow-x-auto rounded-lg border border-gray-200 dark:border-white/10 mb-6">
          <table className="min-w-full table-auto border-collapse">
            <caption className="sr-only">Equipment energy summary</caption>
            <thead>
              <tr className="bg-gray-50 dark:bg-white/5">
                <th
                  scope="col"
                  className="border-b border-gray-200 dark:border-white/10 p-3 text-left font-semibold text-gray-700 dark:text-gray-200"
                >
                  Equipment
                </th>
                <th
                  scope="col"
                  className="border-b border-gray-200 dark:border-white/10 p-3 text-left font-semibold text-gray-700 dark:text-gray-200"
                >
                  Room
                </th>
                <th
                  scope="col"
                  className="border-b border-gray-200 dark:border-white/10 p-3 font-semibold text-gray-700 dark:text-gray-200"
                >
                  Power (kW)
                </th>
                <th
                  scope="col"
                  className="border-b border-gray-200 dark:border-white/10 p-3 font-semibold text-gray-700 dark:text-gray-200"
                >
                  Qty
                </th>
                <th
                  scope="col"
                  className="border-b border-gray-200 dark:border-white/10 p-3 font-semibold text-gray-700 dark:text-gray-200"
                >
                  Hours/day
                </th>
                <th
                  scope="col"
                  className="border-b border-gray-200 dark:border-white/10 p-3 font-semibold text-gray-700 dark:text-gray-200"
                >
                  Monthly (kWh)
                </th>
              </tr>
            </thead>
            <tbody>
              {equipmentList.map((it) => (
                <tr
                  key={it.id}
                  className="hover:bg-gray-50 dark:hover:bg-white/5"
                >
                  <td className="border-b border-gray-100 dark:border-white/5 p-3">
                    {it.name}
                  </td>
                  <td className="border-b border-gray-100 dark:border-white/5 p-3 text-sm text-gray-600 dark:text-gray-300">
                    {it.room || "-"}
                  </td>
                  <td className="border-b border-gray-100 dark:border-white/5 p-3 text-center">
                    {it.powerKw}
                  </td>
                  <td className="border-b border-gray-100 dark:border-white/5 p-3 text-center">
                    {it.qty}
                  </td>
                  <td className="border-b border-gray-100 dark:border-white/5 p-3 text-center">
                    {it.hoursPerDay}
                  </td>
                  <td className="border-b border-gray-100 dark:border-white/5 p-3 text-center font-semibold text-emerald-700 dark:text-emerald-400">
                    {Math.round(calcEnergy(it).monthly)}
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="bg-emerald-50 dark:bg-emerald-900/30">
                <td
                  colSpan={5}
                  className="border-b border-gray-200 dark:border-white/10 p-3 text-right font-semibold text-gray-900 dark:text-white"
                >
                  Total Monthly Consumption
                </td>
                <td className="border-b border-gray-200 dark:border-white/10 p-3 text-center font-bold text-emerald-800 dark:text-emerald-300">
                  {Math.round(total)} kWh
                </td>
              </tr>
            </tfoot>
          </table>
        </div>

        <div className="mt-6 flex flex-col md:flex-row justify-between gap-4 items-center">
          <div className="text-sm text-gray-700 dark:text-gray-300 bg-emerald-50 dark:bg-emerald-900/30 rounded-lg p-4 w-full md:w-auto border border-emerald-200 dark:border-emerald-800">
            <span className="font-semibold text-emerald-700 dark:text-emerald-300">
              Recommendations:
            </span>{" "}
            Replace inefficient lighting, install occupancy sensors, review HVAC
            schedules.
          </div>
          <div>
            <button onClick={onBack} className="btn btn-primary">
              Back to Dashboard
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Report;
